name: custodians
description: A new Flutter project.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.0
  file_picker: ^6.1.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true